version: "3"
services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: "wead/php-ai-samples"
    container_name: "php_ai_sampes"
    hostname: "host_php_ai_sampes"
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
