version: "3"
services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: "wead/tsp-genetic-php"
    container_name: "tsp_genetic_php"
    hostname: "host_tsp_genetic_php"
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
